<?php
/**
 * Table of Content Block
 * Create autogenerated Table of Content
 */

if (!defined('ABSPATH')) {
    exit;
}

class Syntekpro_Toc_Block extends Syntekpro_Base_Block {
    
    protected $block_name = 'toc';
    protected $block_title = 'Table of Content';
    protected $block_description = 'Create autogenerated Table of Content';
    protected $block_icon = 'editor-ul';
    protected $block_category = 'text';
    protected $block_keywords = array('table', 'content', 'toc');
    
    protected $block_attributes = array(
        'title' => array('type' => 'string', 'default' => 'Table of Contents'),
        'headingLevels' => array('type' => 'array', 'default' => array(2, 3)),
        'showTitle' => array('type' => 'boolean', 'default' => true),
        'numbered' => array('type' => 'boolean', 'default' => false),
        'linkColor' => array('type' => 'string', 'default' => '#0073aa')
    );

    public function render_block($attributes, $content) {
        // TODO: Generate TOC from page headings
        $unique_id = 'toc-' . uniqid();
        
        $output = sprintf(
            '<div id="%s" class="syntekpro-toc">%s<ul>%s</ul></div>',
            esc_attr($unique_id),
            $attributes['showTitle'] ? '<h2>' . esc_html($attributes['title']) . '</h2>' : '',
            '<li><a href="#section-1">Section 1</a></li>'
        );
        
        return $output;
    }
}
